
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 26 17:52:12 CDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 33;
  public static final int Class = 15;
  public static final int Op_aritmetico = 31;
  public static final int Entero = 23;
  public static final int Llave_c = 46;
  public static final int Op_booleano = 40;
  public static final int Llave_a = 45;
  public static final int If = 25;
  public static final int Namespace = 19;
  public static final int Void = 16;
  public static final int T_dato = 9;
  public static final int Else = 26;
  public static final int H = 43;
  public static final int Cout = 12;
  public static final int Corchete_c = 48;
  public static final int Corchete_a = 47;
  public static final int Punto = 6;
  public static final int Return = 10;
  public static final int While = 28;
  public static final int Parentesis_c = 42;
  public static final int Cadena = 24;
  public static final int Ampersand = 37;
  public static final int Parentesis_a = 41;
  public static final int For = 29;
  public static final int Std = 20;
  public static final int P_coma = 50;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Simbolo_cout = 7;
  public static final int Flecha = 34;
  public static final int Linea = 2;
  public static final int Op_atribucion = 38;
  public static final int ERROR = 53;
  public static final int Do = 27;
  public static final int Op_logico = 32;
  public static final int Dos_puntos = 5;
  public static final int Const = 36;
  public static final int Especificador = 14;
  public static final int Identificador = 51;
  public static final int Using = 18;
  public static final int Endl = 13;
  public static final int Cin = 11;
  public static final int Multiplicacion = 44;
  public static final int Gato = 4;
  public static final int ParentesisAngular_c = 22;
  public static final int Op_incremento = 39;
  public static final int Numero = 52;
  public static final int Simbolo_cin = 8;
  public static final int ParentesisAngular_a = 21;
  public static final int Include = 17;
  public static final int Main = 49;
  public static final int This = 35;
  public static final int Igual = 30;
  public static final int Comillas = 3;
}

